# Generated by Django 2.1.7 on 2020-01-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_like_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_list',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customuser.CustomUser'),
        ),
    ]
