# Generated by Django 2.1.7 on 2020-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('creator', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(related_name='members', to='customuser.CustomUser')),
            ],
        ),
    ]
